# Generated by Django 3.1.2 on 2020-11-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='borrowed_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
