# Generated by Django 3.1.2 on 2020-11-08 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_auto_20201030_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='due',
        ),
    ]
